package myframebooksotre;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mustaf
 */
public class Mainframe extends javax.swing.JFrame {

    /**
     * Creates new form Mainframe
     */
    public Mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        author = new RSMaterialComponent.RSButtonMaterialIconOne();
        publisher = new RSMaterialComponent.RSButtonMaterialIconOne();
        customer = new RSMaterialComponent.RSButtonMaterialIconOne();
        employee = new RSMaterialComponent.RSButtonMaterialIconOne();
        book = new RSMaterialComponent.RSButtonMaterialIconOne();
        bookorder = new RSMaterialComponent.RSButtonMaterialIconOne();
        order = new RSMaterialComponent.RSButtonMaterialIconOne();
        payment = new RSMaterialComponent.RSButtonMaterialIconOne();
        category = new RSMaterialComponent.RSButtonMaterialIconOne();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Desktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        author.setBackground(new java.awt.Color(153, 153, 153));
        author.setText("Author Registration");
        author.setBackgroundHover(new java.awt.Color(0, 153, 153));
        author.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        author.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        author.setIconTextGap(6);
        author.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LIBRARY_ADD);
        author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorActionPerformed(evt);
            }
        });
        jPanel1.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 320, 60));

        publisher.setBackground(new java.awt.Color(153, 153, 153));
        publisher.setText("Publisher Registration");
        publisher.setBackgroundHover(new java.awt.Color(0, 153, 153));
        publisher.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        publisher.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        publisher.setIconTextGap(6);
        publisher.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LIBRARY_ADD);
        publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherActionPerformed(evt);
            }
        });
        jPanel1.add(publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 320, 60));

        customer.setBackground(new java.awt.Color(153, 153, 153));
        customer.setText("Customer Registration");
        customer.setBackgroundHover(new java.awt.Color(0, 153, 153));
        customer.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        customer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        customer.setIconTextGap(6);
        customer.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jPanel1.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 320, 60));

        employee.setBackground(new java.awt.Color(153, 153, 153));
        employee.setText("Employee Registration");
        employee.setBackgroundHover(new java.awt.Color(0, 153, 153));
        employee.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        employee.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        employee.setIconTextGap(6);
        employee.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });
        jPanel1.add(employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 320, 60));

        book.setBackground(new java.awt.Color(153, 153, 153));
        book.setText("Book Registration");
        book.setBackgroundHover(new java.awt.Color(0, 153, 153));
        book.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        book.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        book.setIconTextGap(6);
        book.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BOOK);
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jPanel1.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 320, 60));

        bookorder.setBackground(new java.awt.Color(153, 153, 153));
        bookorder.setText("Book Order");
        bookorder.setBackgroundHover(new java.awt.Color(0, 153, 153));
        bookorder.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        bookorder.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bookorder.setIconTextGap(6);
        bookorder.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BOOK);
        bookorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookorderActionPerformed(evt);
            }
        });
        jPanel1.add(bookorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 320, 60));

        order.setBackground(new java.awt.Color(153, 153, 153));
        order.setText("Order ");
        order.setBackgroundHover(new java.awt.Color(0, 153, 153));
        order.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        order.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        order.setIconTextGap(6);
        order.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.WORK);
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        jPanel1.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 320, 60));

        payment.setBackground(new java.awt.Color(153, 153, 153));
        payment.setText("Payment");
        payment.setBackgroundHover(new java.awt.Color(0, 153, 153));
        payment.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        payment.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        payment.setIconTextGap(6);
        payment.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PAYMENT);
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });
        jPanel1.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 320, 60));

        category.setBackground(new java.awt.Color(153, 153, 153));
        category.setText("Category");
        category.setBackgroundHover(new java.awt.Color(0, 153, 153));
        category.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        category.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        category.setIconTextGap(6);
        category.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SUBTITLES);
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        jPanel1.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 320, 60));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book Store Forms");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 370, 130));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("---------------------------");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 370, 130));

        Desktop.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 800));
        Desktop.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, -10, -1, -1));

        getContentPane().add(Desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1200, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
        Category cat = new Category();
        // Desktop.add(cat);
        cat.setVisible(true);
    }//GEN-LAST:event_categoryActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
        Payment pay = new Payment();
        // Desktop.add(pay);
        pay.setVisible(true);

    }//GEN-LAST:event_paymentActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        // TODO add your handling code here:
        Order ord= new Order();
        //Desktop.add(ord);
        ord.setVisible(true);
    }//GEN-LAST:event_orderActionPerformed

    private void bookorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookorderActionPerformed
        // TODO add your handling code here:
        BookOrder boor= new BookOrder();
        //Desktop.add(boor);
        boor.setVisible(true);

    }//GEN-LAST:event_bookorderActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        // TODO add your handling code here:
        Book bo= new Book();
        //Desktop.add(bo);
        bo.setVisible(true);
    }//GEN-LAST:event_bookActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        // TODO add your handling code here:
        Employee emp = new Employee();
        //Desktop.add(emp);
        emp.setVisible(true);

    }//GEN-LAST:event_employeeActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
        Customer cust = new Customer();
        //Desktop.add(cust);
        cust.setVisible(true);

    }//GEN-LAST:event_customerActionPerformed

    private void publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherActionPerformed
        // TODO add your handling code here:
        Publisher pub = new Publisher();
        // Desktop.add(pub);
        pub.setVisible(true);
    }//GEN-LAST:event_publisherActionPerformed

    private void authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorActionPerformed
        // TODO add your handling code here:
        Author auth = new Author();
        // Desktop.add(auth);
        auth.setVisible(true);
    }//GEN-LAST:event_authorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private RSMaterialComponent.RSButtonMaterialIconOne author;
    private RSMaterialComponent.RSButtonMaterialIconOne book;
    private RSMaterialComponent.RSButtonMaterialIconOne bookorder;
    private RSMaterialComponent.RSButtonMaterialIconOne category;
    private RSMaterialComponent.RSButtonMaterialIconOne customer;
    private RSMaterialComponent.RSButtonMaterialIconOne employee;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private RSMaterialComponent.RSButtonMaterialIconOne order;
    private RSMaterialComponent.RSButtonMaterialIconOne payment;
    private RSMaterialComponent.RSButtonMaterialIconOne publisher;
    // End of variables declaration//GEN-END:variables
}
